# Generated by Django 5.0.7 on 2024-07-18 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('m2_construidos', models.FloatField()),
                ('m2_totales', models.FloatField()),
                ('cantidad_estacionamientos', models.IntegerField()),
                ('cantidad_habitaciones', models.IntegerField()),
                ('cantidad_banos', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('precio_mensual', models.IntegerField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmueblesApp.comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmueblesApp.region')),
                ('tipo_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmueblesApp.tipoinmueble')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmueblesApp.region'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_personal', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('arrendatario', 'Arrendatario'), ('arrendador', 'Arrendador')], default='arrendatario', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField()),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmueblesApp.inmueble')),
                ('arrendatario', models.ForeignKey(limit_choices_to={'tipo_usuario': 'arrendatario'}, on_delete=django.db.models.deletion.CASCADE, to='inmueblesApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='inmueble',
            name='arrendador',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'arrendador'}, on_delete=django.db.models.deletion.CASCADE, to='inmueblesApp.usuario'),
        ),
    ]
