# Generated by Django 5.0.7 on 2024-07-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://guttche.cl/wp-content/uploads/2024/01/sinfoto.png', null=True),
        ),
    ]
